ALTER TABLE "alumno" RENAME COLUMN "fechaNacimiento" TO "fecha_nacimiento";--> statement-breakpoint
ALTER TABLE "alumno" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "alumno" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "alumno" RENAME COLUMN "borradoEn" TO "borrado_en";--> statement-breakpoint
ALTER TABLE "cuota" RENAME COLUMN "planificacionCursoId" TO "planificacion_curso_id";--> statement-breakpoint
ALTER TABLE "cuota" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "cuota" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "cuota" RENAME COLUMN "borradoEn" TO "borrado_en";--> statement-breakpoint
ALTER TABLE "curso" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "curso" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "curso" RENAME COLUMN "borradoEn" TO "borrado_en";--> statement-breakpoint
ALTER TABLE "inscripcion_alumno" RENAME COLUMN "alumnoId" TO "alumno_id";--> statement-breakpoint
ALTER TABLE "inscripcion_alumno" RENAME COLUMN "planificacionCursoId" TO "planificacion_curso_id";--> statement-breakpoint
ALTER TABLE "inscripcion_alumno" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "inscripcion_alumno" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "inscripcion_alumno" RENAME COLUMN "borradoEn" TO "borrado_en";--> statement-breakpoint
ALTER TABLE "pago_cuota_alumno" RENAME COLUMN "inscripcionAlumnoId" TO "inscripcion_alumno_id";--> statement-breakpoint
ALTER TABLE "pago_cuota_alumno" RENAME COLUMN "cuotaId" TO "curso_id";--> statement-breakpoint
ALTER TABLE "pago_cuota_alumno" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "pago_cuota_alumno" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "pago_cuota_alumno" RENAME COLUMN "borradoEn" TO "borrado_en";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "precioCuota" TO "precio_cuota";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "fechaInicio" TO "fecha_inicio";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "fechaFin" TO "fecha_fin";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "cursoId" TO "curso_id";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "creadoEn" TO "creado_en";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "actualizadoEn" TO "actualizado_en";--> statement-breakpoint
ALTER TABLE "planificacion_curso" RENAME COLUMN "borradoEn" TO "borrado_en";